import React, { FC, useState } from "react";

import { addDoc } from "firebase/firestore";

const countries: String[] = [
  "afghanistan",
  "africa",
  "albania",
  "algeria",
  "angola",
  "antarctica",
  "argentina",
  "armenia",
  "asia",
  "asia-pacific",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bermuda",
  "bhutan",
  "bolivia",
  "bosnia-herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina-faso",
  "burundi",
  "cambodia",
  "cameroon",
  "canada",
  "cape-verde",
  "central-african-republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "comoros",
  "costa-rica",
  "croatia",
  "cuba",
  "cyprus",
  "czech-republic",
  "democratic-republic-of-the-congo",
  "denmark",
  "djibouti",
  "doklam",
  "dominica",
  "dominican-republic",
  "east-timor",
  "ecuador",
  "egypt",
  "el-salvador",
  "equatorial-guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "europe",
  "fiji",
  "finland",
  "france",
  "gabon",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "grenada",
  "guatemala",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "honduras",
  "hong-kong",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "isle-of-man",
  "israel",
  "italy",
  "ivory-coast",
  "jamaica",
  "japan",
  "jordan",
  "kashmir",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kosovo",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latin-america",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "lithuania",
  "luxembourg",
  "macau",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall-islands",
  "mauritania",
  "mauritius",
  "mexico",
  "middle-east",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar",
  "nagorno-karabakh",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new-caledonia",
  "new-zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "niue",
  "north-korea",
  "north-macedonia",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "palestine",
  "panama",
  "papua-new-guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "puerto-rico",
  "qatar",
  "republic-of-the-congo",
  "romania",
  "russia",
  "rwanda",
  "saint-kitts-and-nevis",
  "saint-vincent-and-the-grenadines",
  "samoa",
  "sao-tome-and-principe",
  "saudi-arabia",
  "senegal",
  "serbia",
  "seychelles",
  "sierra-leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon-islands",
  "somalia",
  "south-africa",
  "south-korea",
  "south-sudan",
  "spain",
  "sri-lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "taiwan",
  "tajikistan",
  "tanzania",
  "thailand",
  "the-gambia",
  "tibet",
  "togo",
  "tokelau",
  "tonga",
  "trinidad-and-tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "tuvalu",
  "uganda",
  "ukraine",
  "united-arab-emirates",
  "united-kingdom",
  "united-states",
  "uruguay",
  "us-&-canada",
  "uzbekistan",
  "vanuatu",
  "vatican",
  "venezuela",
  "vietnam",
  "wales",
  "western-sahara",
  "yemen",
  "zambia",
  "zimbabwe"
]

const countriesDisplay: String[] = [
  "Afghanistan",
  "Africa",
  "Albania",
  "Algeria",
  "Angola",
  "Antarctica",
  "Argentina",
  "Armenia",
  "Asia",
  "Asia Pacific",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic Of The Congo",
  "Denmark",
  "Djibouti",
  "Doklam",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Europe",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle Of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kashmir",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latin America",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Middle East",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Nagorno Karabakh",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic Of The Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts And Nevis",
  "Saint Vincent And The Grenadines",
  "Samoa",
  "Sao Tome And Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "The Gambia",
  "Tibet",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Us & Canada",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

let New: FC<dbProps> = ({ teams, userID }) => {
  
  let [name, setName] = useState("");
  let [country, setCountry] = useState("");
  let [lat, setLat] = useState(0);
  let [long, setLong] = useState(0);

  let addNewMember = (
    name: string,
    lat: number,
    long: number,
    country: string
  ) => {
    addDoc(teams, {
      uid: userID,
      member_name: name,
      lat: lat,
      long: long,
      country: country,
    });
  };

  return (
    <div className="addMemberWrapper">
      <h2 className="manageTitle">Add a new team member</h2>
      <div className="addMemberFlex">
        <div className="labels">
          <span>Name{" "}</span>
          <span>Latitude{" "}</span>
          <span>Longitude{" "}</span>
          <span>Country{" "}</span>
        </div>
        <div className="inputs">
          <input
            name="name"
            value={name}
            onChange={(e) => {
              setName(e.target.value);
            }}
          />
          <input
            name="latitude"
            value={lat}
            type="number"
            onChange={(e) => {
              let num = Number(e.target.value);
              setLat(num);
            }}
          />
          <input
            name="longitude"
            value={long}
            type="number"
            onChange={(e) => {
              let num = Number(e.target.value);
              setLong(num);
            }}
          />
          <select
            name="country"
            value={country}
            onChange={(e) => {
              setCountry(e.target.value);
            }}>
            <option value="">Select a Country</option>
            {countries.map((c, index) => {
              return <option value={c}>{countriesDisplay[index]}</option>;
            })}
          </select>
        </div>
        <button onClick={(e) =>
          addNewMember(name, lat, long, country)
        }>
        Add New Member
        </button>
      </div>
    </div>
  );
};

export default New;
